name: example
description: Flame Splash Screen Example

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame_splash_screen:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

