os:
- linux
sudo: required
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

cache:
  directories:
    - $HOME/.pub-cache

before_script:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - mv flutter $HOME/flutter
  - export PATH=$HOME/flutter/bin:$PATH
  - flutter doctor -v

script:
  - set -e
  - "./format.sh"
  - set +e
  - flutter test

