name: flame_splash_screen
description: Style your flame/flutter game with a beautiful splash screen. Simple to use but very customizable.
version: 0.0.1
homepage: https://github.com/flame-engine/flame_splash_screen

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: 4.1.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/flame-logo-white.gif
   - assets/flame-logo-black.gif
