name: flame_splash_screen
description: Style your flame game with a beautiful splash screen with logo reveal. Simple to use but very customizable.
version: 0.1.0
homepage: https://github.com/flame-engine/flame_splash_screen

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 0.0.1
  mockito: ^5.0.16
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/
