name: flame_splash_screen
description: Style your flame game with a beautiful splash screen with logo reveal. Simple to use but very customizable.
version: 0.1.0
homepage: https://github.com/flame-engine/flame_splash_screen

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^3.2.2
  flame_lint:
    git: https://github.com/flame-engine/flame_lint
  mockito: ^5.0.9
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/
