name: flame_splash_screen
description: Flame splash screen widget
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/flame-logo-white.gif
   - assets/flame-logo-black.gif
